// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcfPrnfl0urJpi6aINxsxLCH2Txp-msrc',
    appId: '1:484751014681:web:5699a2724345a1ac0ca388',
    messagingSenderId: '484751014681',
    projectId: 'orbitalflutterhawkerbro',
    authDomain: 'orbitalflutterhawkerbro.firebaseapp.com',
    storageBucket: 'orbitalflutterhawkerbro.appspot.com',
    measurementId: 'G-LQWEH52ZD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx3KbABiG19bpfUtvEQqZJBFNSdDrvoD0',
    appId: '1:484751014681:android:8a6c2e55414ec3080ca388',
    messagingSenderId: '484751014681',
    projectId: 'orbitalflutterhawkerbro',
    storageBucket: 'orbitalflutterhawkerbro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxVOet3ECtpkVK46VIg1BWP-nXhqerTiw',
    appId: '1:484751014681:ios:0249493a6a91f8400ca388',
    messagingSenderId: '484751014681',
    projectId: 'orbitalflutterhawkerbro',
    storageBucket: 'orbitalflutterhawkerbro.appspot.com',
    androidClientId:
        '484751014681-mkk29kmdqtepcfkq6k7pqk535es54d33.apps.googleusercontent.com',
    iosClientId:
        '484751014681-lcjstofulfpk7eaqijr27vvnlra28utm.apps.googleusercontent.com',
    iosBundleId: 'com.example.hawkerbro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxVOet3ECtpkVK46VIg1BWP-nXhqerTiw',
    appId: '1:484751014681:ios:9243234c023ce8000ca388',
    messagingSenderId: '484751014681',
    projectId: 'orbitalflutterhawkerbro',
    storageBucket: 'orbitalflutterhawkerbro.appspot.com',
    androidClientId:
        '484751014681-mkk29kmdqtepcfkq6k7pqk535es54d33.apps.googleusercontent.com',
    iosClientId:
        '484751014681-2usrrom8hqa0kqjqle5qarqs9c4bov4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.hawkerbro.RunnerTests',
  );
}
